%File name is pb01_40.m and this file is for Problem 1.40.

%You will need the normal density function N(0,1) for this problem.
%A special MATLAB function function n01(x) is provided for this
%purpose.  It is given in file n01.m.

%Part (a):
%The upper limit for the integration in part (a) can be found by trial-
%and-error.  Anywhere around 10 to 12 usually provides enough accuracy.
%Ans:  Prob[x>4.5] = 3.39767e-06 (approx.)

%Part(b):
%The Feller formula for x=6.5 yields about 4.10701e-11, whereas MATLAB
%integration gives 4.01600e-11.  The Feller formula is still in
%error by about 2 percent for x=6.5.
