%File name is pb03_28.m and this file is for Problem 3.28.

%The power spectral density (psd) must be integrated over the specified
%frequency range.  Do this numerically with either quad8 or quad.

%The function to be integrated over positive frequency (including the
%coefficient) is given in file psd328.m and the function name is psd328.
%For convenience, let sigma=1 and T=2.

%Answer:  Approxiately 90 percent of the total power is contained in
%the primary lobe, and about 95 percent is contained in both the
%primary and first side lobes put together.
