%File name is pb03_27.m and this file is for Problem 3.27.

%The output power spectral density (psd) is
%      psd=(sinc(u))^2 * (1/(1+omega^2))
%where u=omega/2.

%A special function function describing the function to be integrated
%(including the 1/pi coefficient) is provided in file psd327.m and
%the function name is psd327.

%This problem is best worked interactively using MATLAB's quad8 or
%quad for the numerical integration.  Experiment with the lower and
%upper lmits on the integration.

%Your answer should be close to 1/e, which is about .3679.
